### ISSUE TITLE
Business Diversity

### ISSUE THREAD

**Issue by hgunc** [civic-data-design-lab/atlas-lighting#161]
Should display how many cells are selected for each category. Right now it displays, 1,2,3,4
<img width="295" alt="screen shot 2017-03-08 at 2 58 18 pm" src="https://cloud.githubusercontent.com/assets/24460295/23721451/cc8897c6-040f-11e7-87cf-e4961a08e908.png">

**Comment by egeozin** [comment]
But this is contrary to all other charts, right?

Because all other chaets display median of the data.

And specifically for diversity charts is point of interest is the diversity metric.right?

So I want to make sure that this.is thr only the.case that we show thr number of selected cells?



On Wed, Mar 8, 2017 at 2:59 PM -0500, "hgunc" <notifications@github.com<mailto:notifications@github.com>> wrote:


Should display how many cells are selected for each category. Right now it displays, 1,2,3,4
[screen shot 2017-03-08 at 2 58 18 pm]<https://cloud.githubusercontent.com/assets/24460295/23721451/cc8897c6-040f-11e7-87cf-e4961a08e908.png>

**Comment by egeozin** [comment]
fixed in 0720d19
