### ISSUE TITLE
Instagram density and likes chart can not be brushed

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#41]
There is an overlay of Google Street view image.

<img width="760" alt="instagram_density_and_likes" src="https://cloud.githubusercontent.com/assets/14356218/22797607/df9645f0-eecc-11e6-9837-5d629acd4eba.png">

**Comment by egeozin** [comment]
When you zoom or interact with the map, you can edit easily. 
Probably related to selectedCharts, or updateCharts function.

**Comment by cosmicespresso** [comment]
It only happens when I keep on refreshing with this chart open: http://localhost:8080/view/grid.html#LA*ins_likes 
When I start from root (http://localhost:8080/view/grid.html#LA) it seems to be fine. 

Two possible causes:
1. use of opacity rather than display to toggle visibility
2. the nested conditionals in updateCharts, just like you mention above

**Comment by egeozin** [comment]
Added two "display:none" lines for the street view fixed the problem.
