### ISSUE TITLE
grid map does not hold the OBI timeline selection

### ISSUE THREAD

**Issue by cosmicespresso** [civic-data-design-lab/atlas-lighting#80]
the usual +1 sec additional filtering is occurring again

**Comment by egeozin** [comment]
Yep, it now happens on OBI timeline filter,(case 1)

also when; 
(case 2)a chart is filtered(brushed)  => selected business types filter is released but not the chart brush => 1 sec additional filtering.

I know that now these will be easier to solve after that dirty but functional filtering function called filterCells in grid_map.js. You can check that function to see why it carries that timeline filtering the way it does. What I considered while producing that function is that I wanted to carry the essentials from the filterhour function. Now, appropriate filtering takes place when you drop the OBI into right panel but there is an additional filtering due to drawing the charts again and probably executing the last branch of that function.

I think with additional flagging we would be able to prevent that additional filtering on OBI interaction. If you have time,  check how that flagging works for preventing double filtering on other charts except the cases above.

**Comment by cosmicespresso** [comment]
I'm a bit lost with the new functions.... :/ 

In addition, you have commented out `filterhour` but you call it from `timeSelectorReset` and `timeSelectorResetBack`. Do we need the latter functions?

![image](https://cloud.githubusercontent.com/assets/10440556/23148696/44ff2466-f7b5-11e6-9662-961780121dda.png)

**Comment by egeozin** [comment]
We don't need them, I can try to explain it better tmw morning if you want.

**Comment by cosmicespresso** [comment]
ok so I have some progress on the primary issue (see screengrab) - this is the `renderlet` of the Light Av chart. The chart is rendered every time, and hence the `else` case is executed on every change of the time filter. 

The issue might lie with the `window.newData` object (?)

![image](https://cloud.githubusercontent.com/assets/10440556/23150656/023967f0-f7c3-11e6-8ef8-b48af4c8c533.png)

**Comment by cosmicespresso** [comment]
following the above thoughts
1. The first clause of the `if` statement above gets executed only once, on load. `window.filtered` is otherwise always `false`. Does that sound right?
2. I am 99% sure the problem with the OBI chart is that the `displayCells` is executed right on top of of the interaction with the time slider.

**Comment by egeozin** [comment]
Yes, and it is also executed when a tag in the business types and instagram topics chart is clicked(selected and deselected),


```javascript
// @ tag_cloud_chart.js
            .on('click', function(){
                //if (!cellSelected){
                    if (d3.select(this).classed("active")) {
                        d3.select(this).classed("active", false)
                        var category = d3.select(this).text();
                        var ind = selectedTypes.indexOf(category);
                        selectedTypes.splice(ind, 1);
                        if (selectedTypes.length === 0){
                            typeSelected = false;
                            window.filtered = false;
                            filterCells(originalData);
                        } else {
                            window.filtered = false;
                            filterCells(cellsData);
                        }
                    } else {
                        typeSelected = true;
                        d3.select(this).classed("active", true);
                        var category = d3.select(this).text();
                        selectedTypes.push(category);
                        window.filtered = false;
                        filterCells(cellsData);
                        }
             });
```

**Comment by cosmicespresso** [comment]
I think I fixed it - 224102c (check when you have the time)

**Comment by egeozin** [comment]
I think it's working, why did you reopened?

**Comment by egeozin** [comment]
Ah, ok! now if a brush is selected in any row chart and if there is an interaction with business types chart, then it displays all the cells, instead of displaying the first filter
