### ISSUE TITLE
Business Diversity Bubble Chart: Bubbles becomes invisible after a flash.

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#81]
Could that be related with a shared css of busDiv chart and the one in front_map's ?

**Comment by cosmicespresso** [comment]
I feel that could be similar to other bug we encounter in the OBI. Something is rendering on top of the current selection, like a n+1 render callbacks. Looking into it.

**Comment by cosmicespresso** [comment]
**Update**
The reason why it doesn't show is because the `r` variable for the bubbles is equal to `0`. That in turn happens because of the `updateAndDraw` function.
When I comment its contents out entirely like below, the diversity shows fine, and the OBI chart does not have the weird behavior either.
![image](https://cloud.githubusercontent.com/assets/10440556/23187944/ce59edf4-f85a-11e6-9b5b-543da3291fa0.png)

![image](https://cloud.githubusercontent.com/assets/10440556/23188096/6d6fa8c0-f85b-11e6-9a76-ff1330f3bb97.png)

Once I click around and interact, its gone again, but the map is filtered so the functionality is intact.
![image](https://cloud.githubusercontent.com/assets/10440556/23188108/7ff8ded0-f85b-11e6-8236-9476dd9bc4ad.png)

**Comment by egeozin** [comment]
Ok, but if it happens when ndx is removed and updated why don't we see that kind of change in others as well?

(it was plain busDiv in the first place, then I changed to window.busDiv however the bug persists)

**Comment by cosmicespresso** [comment]
True point. I'm afraid that I'm a bit lost in all the objects we are now using to control the data - `window.newData`, `data` and `filtered`.  The latter might be introducing a dangerous namespacing issue with the `window.filtered` btw. I will rename it to `filteredData`.

**Comment by egeozin** [comment]
Could this be our problem: this is the only dimension selector that uses minBDiv and maxBDiv that are computed early, that is not bound to new data.
 
```javascript
var busDivDimension = window.ndx.dimension(function (d) {
      return (Math.round((d.b_diversity - minBDiv) / (maxBDiv - minBDiv) * 3) + 1) || 0
});
```

Edit: This is not our problem.

**Comment by egeozin** [comment]
Also: I've updated the updateAndDraw function to adapt window.count to altered data, but problem persists.

```javascript
.radiusValueAccessor(function (p) {
            return p.value/window.count*chartHeightBusDiv*4/5;
        })
```

**Comment by egeozin** [comment]
Good news:

Business diversity will live! (Although it has to use bars from now on.)

<img width="365" alt="i_cried" src="https://cloud.githubusercontent.com/assets/14356218/23489303/7e211586-febf-11e6-8ae0-a2bfbb116cb2.png">

I will shortly update the website.
